services:
  db:
    image: ankane/pgvector
    container_name: ctrl-fpp-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ctrl-fpp-backend
    depends_on: [db]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file: [.env]
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./backend/vectorstore:/app/vectorstore
      - ./backend/data:/app/data/docs

  frontend:
    profiles: ["ui"] # ← only runs with `--profile ui`
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ctrl-fpp-frontend
    env_file: [.env]
    depends_on: [backend]
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app # remove in prod, keep in dev

volumes:
  pgdata:
