services:
  db:
    image: ankane/pgvector
    container_name: ctrl-fpp-db-1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ctrl-fpp-backend
    depends_on: [db]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file: [.env]
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./backend/vectorstore:/app/vectorstore
      - ./backend/data:/app/data/docs

  frontend:
    profiles: ["ui"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ctrl-fpp-frontend
    env_file: [.env]
    depends_on: [backend]
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app

  pgadmin:
    image: dpage/pgadmin4
    container_name: ctrl-fpp-pgadmin-1
    depends_on: [db]
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file: [.env]
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
